apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-hwc-subchart
  namespace: test
spec:
  project: default
  source:
    repoURL: 'https://github.com/participant-two/hwc-subchart'
    path: dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
 
